import React from 'react';
import { Bot, LineChart, Zap, BrainCircuit, Globe, TrendingUp } from 'lucide-react';
import { Fund } from './types';

export const MOCK_FUNDS: Fund[] = [
  {
    id: '1',
    ticker: 'ARBIT',
    name: 'Arbitrage Master V1',
    description: 'A low-latency triangular arbitrage bot targeting UNI/SUSHI pools on Ethereum. Features MEV protection logic built directly into the workflow.',
    creator: '0xAlpha...42a',
    marketCap: 42000,
    price: 0.0042,
    change24h: 12.5,
    replies: 45,
    volume: '125 ETH',
    bondingProgress: 65,
    icon: <Bot className="text-cyber-neon" />,
    chartData: Array.from({ length: 20 }, (_, i) => ({ time: `${i}`, value: 10 + Math.random() * 5 + i * 0.5 })),
  },
  {
    id: '2',
    ticker: 'SENTI',
    name: 'Twitter Sentiment AI',
    description: 'Scrapes CryptoTwitter for narrative shifts using GPT-4o analysis. Buys trending tickers automatically when positive sentiment crosses 85%.',
    creator: 'ElonDoge',
    marketCap: 12500,
    price: 0.0012,
    change24h: -2.3,
    replies: 12,
    volume: '15 ETH',
    bondingProgress: 22,
    icon: <Globe className="text-cyber-pink" />,
    chartData: Array.from({ length: 20 }, (_, i) => ({ time: `${i}`, value: 5 + Math.random() * 2 })),
  },
  {
    id: '3',
    ticker: 'WHALE',
    name: 'Whale Wallet Tracker',
    description: 'Monitors a curated list of top 100 whale wallets. Copies trades with a 5-minute delay to avoid front-running traps.',
    creator: 'DeepSea',
    marketCap: 89000,
    price: 0.0089,
    change24h: 34.2,
    replies: 128,
    volume: '450 ETH',
    bondingProgress: 92,
    icon: <BrainCircuit className="text-cyber-purple" />,
    chartData: Array.from({ length: 20 }, (_, i) => ({ time: `${i}`, value: 20 + Math.pow(i, 1.5) * 0.1 + Math.random() * 5 })),
  },
  {
    id: '4',
    ticker: 'YIELD',
    name: 'Stable Yield Farmer',
    description: 'Auto-compounds stablecoin positions across Aave and Compound. Optimizes for gas efficiency and highest APY.',
    creator: 'DeFiDad',
    marketCap: 5000,
    price: 0.0005,
    change24h: 0.5,
    replies: 4,
    volume: '2 ETH',
    bondingProgress: 8,
    icon: <TrendingUp className="text-green-400" />,
    chartData: Array.from({ length: 20 }, (_, i) => ({ time: `${i}`, value: 2 + i * 0.05 })),
  },
];
